import FormalConjecturesUtil

/-!
# Ibragimov–Iosifescu conjecture for φ-mixing sequences

Let $(X_n)_{n \in \mathbb{N}}$ be a strictly stationary, centered, $\phi$-mixing sequence of
real random variables with $\mathbb{E}(X_0^2) < \infty$ and
$\sigma_n^2 := \operatorname{Var}(S_n) \to +\infty$, where $S_n$ denotes the $n$-th partial sum.
Then, per Ibragimov, $S_n / \sigma_n$ converges in distribution to $N(0, 1)$
(a central limit theorem), and, per Iosifescu, the partial-sum process
$t \mapsto S_{[nt]} / \sigma_n$, $t \in [0, 1]$, converges weakly to standard Brownian motion
(a weak invariance principle).

Here the sequence is indexed by $\mathbb{N} = \{0, 1, 2, \dots\}$ and $S_n := \sum_{j < n} X_j$;
by strict stationarity this agrees in law with the convention $S_n = \sum_{j = 1}^n X_j$ used in
the sources. The weak invariance principle is stated in $C([0, 1], \mathbb{R})$ for the polygonal
(linearly interpolated) partial-sum process, which is equivalent to the formulation for the step
process $S_{[nt]} / \sigma_n$ in the Skorokhod space $D[0, 1]$.

*References:*
- [Wikipedia](https://en.wikipedia.org/wiki/Ibragimov%E2%80%93Iosifescu_conjecture_for_%CF%86-mixing_sequences)
- [IL71] I. A. Ibragimov and Yu. V. Linnik, _Independent and Stationary Sequences of Random
  Variables_, Wolters-Noordhoff, Groningen, 1971, p. 393, problem 3.
- [Io77] M. Iosifescu, _Limit theorems for φ-mixing sequences, a survey_. In: Proceedings of the
  Fifth Conference on Probability Theory, Brașov, 1974, pp. 51-57. Publishing House of the Romanian
  Academy, Bucharest, 1977.
- [Pe90] M. Peligrad, _On Ibragimov–Iosifescu conjecture for φ-mixing sequences_.
  Stochastic Processes and their Applications 35 (1990), 293-308.
  [doi:10.1016/0304-4149(90)90008-G](https://doi.org/10.1016/0304-4149(90)90008-G)
-/

open MeasureTheory ProbabilityTheory Filter Topology
open scoped unitInterval

namespace IbragimovIosifescuConjectureForMixingSequences

variable {Ω : Type*} [MeasurableSpace Ω] (X : ℕ → Ω → ℝ) (μ : Measure Ω)

/-
### Strict stationarity and φ-mixing
-/

/-- The $\sigma$-algebra $\sigma(X_j, j \in s)$ generated by the random variables $X_j$,
$j \in s$. -/
def sigmaGen (s : Set ℕ) : MeasurableSpace Ω :=
  ⨆ j ∈ s, MeasurableSpace.comap (X j) inferInstance

/-- A sequence $(X_n)_{n \in \mathbb{N}}$ of random variables is *strictly stationary* if, for
every $k$, the shifted sequence $(X_{n + k})_{n \in \mathbb{N}}$ has the same joint distribution as
$(X_n)_{n \in \mathbb{N}}$. -/
def IsStrictlyStationary : Prop :=
  ∀ k : ℕ, IdentDistrib (fun ω n ↦ X (n + k) ω) (fun ω n ↦ X n ω) μ μ

/-- The $\phi$-mixing coefficients of a sequence $X = (X_n)_{n \in \mathbb{N}}$:
$$\phi_X(n) := \sup\{|\mu(B \mid A) - \mu(B)| :
  A \in \mathcal{F}^m,\ \mu(A) > 0,\ B \in \mathcal{F}_{m + n},\ m \in \mathbb{N}\},$$
where $\mathcal{F}^m = \sigma(X_j, j \le m)$ and $\mathcal{F}_{m + n} = \sigma(X_j, j \ge m + n)$.
The supremum is taken over the sets $A$ of positive probability, so that the conditional
probability $\mu(B \mid A)$ is defined. -/
noncomputable def phiMixingCoeff (n : ℕ) : ℝ :=
  sSup {r | ∃ (m : ℕ) (A B : Set Ω), MeasurableSet[sigmaGen X (Set.Iic m)] A ∧ 0 < μ A ∧
    MeasurableSet[sigmaGen X (Set.Ici (m + n))] B ∧ r = |(μ[|A]).real B - μ.real B|}

/-- A sequence of random variables is *$\phi$-mixing* if its $\phi$-mixing coefficients satisfy
$\phi_X(n) \to 0$ as $n \to \infty$. -/
def IsPhiMixing : Prop :=
  Tendsto (phiMixingCoeff X μ) atTop (𝓝 0)

/-
### Partial sums and the partial-sum process
-/

/-- The partial sums $S_n := \sum_{j < n} X_j$. -/
def partialSum (n : ℕ) (ω : Ω) : ℝ :=
  ∑ j ∈ Finset.range n, X j ω

/-- The standard deviation $\sigma_n := \sqrt{\operatorname{Var}(S_n)}$ of the partial sum $S_n$. -/
noncomputable def partialSumStdDev (n : ℕ) : ℝ :=
  √(variance (partialSum X n) μ)

/-- The normalized partial sum $S_n / \sigma_n$. -/
noncomputable def normalizedPartialSum (n : ℕ) (ω : Ω) : ℝ :=
  partialSum X n ω / partialSumStdDev X μ n

/-- The normalized partial sum is a real random variable. -/
lemma measurable_normalizedPartialSum (hX : ∀ n, Measurable (X n)) (n : ℕ) :
    Measurable (normalizedPartialSum X μ n) := by
  unfold normalizedPartialSum partialSum
  fun_prop

/-- The (linearly interpolated) partial-sum process $W_n : [0, 1] \to \mathbb{R}$,
$$W_n(t) := \frac{1}{\sigma_n} \sum_{j < n} X_j \min(1, \max(0, nt - j))
  = \frac{S_{[nt]} + (nt - [nt]) X_{[nt]}}{\sigma_n},$$
that is, the polygonal path through the points $(k / n, S_k / \sigma_n)$, $0 \le k \le n$, viewed
as a random element of $C([0, 1], \mathbb{R})$. -/
noncomputable def partialSumProcess (n : ℕ) (ω : Ω) : C(I, ℝ) where
  toFun t :=
    (∑ j ∈ Finset.range n, X j ω * min 1 (max 0 (n * (t : ℝ) - j))) / partialSumStdDev X μ n
  continuous_toFun := by fun_prop

/-- The Borel $\sigma$-algebra on the path space $C([0, 1], \mathbb{R})$. -/
local instance : MeasurableSpace C(I, ℝ) := borel _

local instance : BorelSpace C(I, ℝ) := ⟨rfl⟩

/-
### Brownian motion
-/

/-- A measure $W$ on $C([0, 1], \mathbb{R})$ is the *Wiener measure* (the law of standard Brownian
motion on $[0, 1]$) if it is a probability measure under which the coordinate process
$w \mapsto w(t)$ starts at $0$ almost surely, has independent increments, and has Gaussian
increments $w(t) - w(s) \sim N(0, t - s)$ for $s \le t$. -/
structure IsWienerMeasure (W : Measure C(I, ℝ)) : Prop where
  isProbabilityMeasure : IsProbabilityMeasure W
  ae_zero : ∀ᵐ w ∂W, w 0 = 0
  iIndepFun_increments : ∀ (k : ℕ) (t : Fin (k + 1) → I), StrictMono t →
    iIndepFun (fun i : Fin k ↦ fun w : C(I, ℝ) ↦ w (t i.succ) - w (t i.castSucc)) W
  map_increment_eq : ∀ s t : I, s ≤ t →
    W.map (fun w : C(I, ℝ) ↦ w t - w s) = gaussianReal 0 (Real.toNNReal (t - s))

/-
### The conjectures
-/

variable [IsProbabilityMeasure μ]

/-- **Ibragimov's conjecture** (central limit theorem for $\phi$-mixing sequences).

Let $(X_n)_{n \in \mathbb{N}}$ be a strictly stationary, centered, $\phi$-mixing sequence of
real random variables such that $\mathbb{E}(X_0^2) < \infty$ and
$\sigma_n^2 := \operatorname{Var}(S_n) \to +\infty$, where $S_n := \sum_{j < n} X_j$.
Then $S_n / \sigma_n$ converges in distribution to the standard normal law $N(0, 1)$. -/
theorem ibragimov_iosifescu_conjecture_for_mixing_sequences.parts.i
    (hX : ∀ n, Measurable (X n))
    (h_stat : IsStrictlyStationary X μ) (h_mix : IsPhiMixing X μ)
    (h_L2 : MemLp (X 0) 2 μ) (h_mean : μ[X 0] = 0)
    (h_var : Tendsto (fun n ↦ variance (partialSum X n) μ) atTop atTop) :
    Tendsto (β := ProbabilityMeasure ℝ)
      (fun n ↦ ⟨μ.map (normalizedPartialSum X μ n), Measure.isProbabilityMeasure_map
        (measurable_normalizedPartialSum X μ hX n).aemeasurable⟩)
      atTop (𝓝 ⟨gaussianReal 0 1, inferInstance⟩) := by
  sorry

end IbragimovIosifescuConjectureForMixingSequences

theorem IbragimovIosifescuConjectureForMixingSequences.ibragimov_iosifescu_conjecture_for_mixing_sequences.parts.i.disproof : ¬ (type_of% @IbragimovIosifescuConjectureForMixingSequences.ibragimov_iosifescu_conjecture_for_mixing_sequences.parts.i) := sorry
